# default controller 
L_gripper_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - L_drive_joint
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    L_drive_joint: {trajectory: 1, goal: 0.01}

L_gripper_velo_traj_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: 
    - L_drive_joint
  gains:
    L_drive_joint: {p: 10, i: 0.1, d: 0.1, i_clamp: 0}
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    L_drive_joint: {trajectory: 1, goal: 0.01}

L_gripper_action_controller:
  type: position_controllers/GripperActionController
  joint: L_drive_joint
  action_monitor_rate: 20
  goal_tolerance: 0.005
  max_effort: 100
  stall_velocity_threshold: 0.01
  stall_timeout: 0.5

# default controller 
R_gripper_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - R_drive_joint
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    R_drive_joint: {trajectory: 1, goal: 0.01}

R_gripper_velo_traj_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: 
    - R_drive_joint
  gains:
    R_drive_joint: {p: 10, i: 0.1, d: 0.1, i_clamp: 0}
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    R_drive_joint: {trajectory: 1, goal: 0.01}

R_gripper_action_controller:
  type: position_controllers/GripperActionController
  joint: R_drive_joint
  action_monitor_rate: 20
  goal_tolerance: 0.005
  max_effort: 100
  stall_velocity_threshold: 0.01
  stall_timeout: 0.5

# No Pid gains specified error fix
gazebo_ros_control:
  pid_gains:
    L_drive_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    L_left_finger_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    L_left_inner_knuckle_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    L_right_outer_knuckle_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    L_right_finger_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    L_right_inner_knuckle_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_drive_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_left_finger_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_left_inner_knuckle_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_right_outer_knuckle_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_right_finger_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    R_right_inner_knuckle_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    