# real_move default controller
gripper_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - drive_joint
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    drive_joint: {trajectory: 1, goal: 0.01}

gripper_velo_traj_controller:
  type: velocity_controllers/JointTrajectoryController
  joints: 
    - drive_joint
  gains:
    drive_joint: {p: 10, i: 0.1, d: 0.1, i_clamp: 0}
  constraints:
    goal_time: 0.5
    stopped_velocity_tolerance: 0.05
    drive_joint: {trajectory: 1, goal: 0.01}

gripper_action_controller:
  type: position_controllers/GripperActionController
  joint: drive_joint
  action_monitor_rate: 20
  goal_tolerance: 0.005
  max_effort: 100
  stall_velocity_threshold: 0.01
  stall_timeout: 0.5

# No Pid gains specified error fix
gazebo_ros_control:
  pid_gains:
    drive_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    left_finger_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    left_inner_knuckle_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    right_outer_knuckle_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    right_finger_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    right_inner_knuckle_joint: {p: 10.0, i: 0.1, d: 0.0, i_clamp: 0.2, antiwindup: false, publish_state: true}
    